### ISSUE TITLE
Removal of `file_browser` from Telescope builtin

### ISSUE THREAD

**Issue by axieax** [jvgrootveld/telescope-zoxide#12]
Seems like Telescope file_browser was removed as a builtin a while ago. I've been using a custom mapping in my config to use the correct file_browser, but think it'll be nice to update the plugin so it works out of the box. I'm happy to make PR if you want, but just wanted to make sure you're cool with having https://github.com/nvim-telescope/telescope-file-browser.nvim as an extra dependency now.

Relevant change:

https://github.com/nvim-telescope/telescope.nvim/issues/1470#issuecomment-974147513

**Comment by jvgrootveld** [comment]
@axieax good find! I don't use this feature myself a lot so didn't walked against this issue yet.

I added this in the default config because the feature was already available out of the box. I don't think it is necessary to add an extra dependency for all users, regarding if they use it. I think we should remove this from the default config and let users choose if they want to add.

I will make the change later and add some documentation in the release how to add it back if wanted.

**Comment by jvgrootveld** [comment]
@axieax I'm sorry, I found little time with my newborn daughter to implement this as discussed. It would be awesome if you could help with a PR.

**Comment by axieax** [comment]
Oh congratulations, that's very exciting news!! 🎉🎉
I've create a PR for this in #19 :))

**Comment by eXvimmer** [comment]
I've added this to the config and it works fine

```lua
mappings = {
["<C-b>"] = {
  action = function(selection)
    vim.cmd("Telescope file_browser path=" .. selection.path .. " select_buffer=true")
  end,
  after_action = function(selection)
    vim.notify("Directory changed to " .. selection.path)
  end,
},
},
```
